import * as schemas from './schemas';
import { z } from 'zod';
export declare class CompanyService {
    getCompanies(filters: z.infer<typeof schemas.CompanyFilterSchema>): Promise<{
        type: import("@prisma/client").$Enums.CompanyType;
        stage: import("@prisma/client").$Enums.FundingStage;
        location: string;
        name: string;
        id: string;
        linkedinUrl: string | null;
        industries: string[];
        createdAt: Date;
        updatedAt: Date;
        tagline: string | null;
        description: string | null;
        website: string | null;
        foundedYear: number | null;
        teamSize: number | null;
        totalFunding: number | null;
    }[]>;
    getCompanyById(id: string): Promise<{
        type: import("@prisma/client").$Enums.CompanyType;
        stage: import("@prisma/client").$Enums.FundingStage;
        location: string;
        name: string;
        id: string;
        linkedinUrl: string | null;
        industries: string[];
        createdAt: Date;
        updatedAt: Date;
        tagline: string | null;
        description: string | null;
        website: string | null;
        foundedYear: number | null;
        teamSize: number | null;
        totalFunding: number | null;
    }>;
    createCompany(data: z.infer<typeof schemas.CompanyCreateSchema>): Promise<{
        type: import("@prisma/client").$Enums.CompanyType;
        stage: import("@prisma/client").$Enums.FundingStage;
        location: string;
        name: string;
        id: string;
        linkedinUrl: string | null;
        industries: string[];
        createdAt: Date;
        updatedAt: Date;
        tagline: string | null;
        description: string | null;
        website: string | null;
        foundedYear: number | null;
        teamSize: number | null;
        totalFunding: number | null;
    }>;
    updateCompany(id: string, data: z.infer<typeof schemas.CompanyUpdateSchema>): Promise<{
        type: import("@prisma/client").$Enums.CompanyType;
        stage: import("@prisma/client").$Enums.FundingStage;
        location: string;
        name: string;
        id: string;
        linkedinUrl: string | null;
        industries: string[];
        createdAt: Date;
        updatedAt: Date;
        tagline: string | null;
        description: string | null;
        website: string | null;
        foundedYear: number | null;
        teamSize: number | null;
        totalFunding: number | null;
    }>;
    deleteCompany(id: string): Promise<{
        type: import("@prisma/client").$Enums.CompanyType;
        stage: import("@prisma/client").$Enums.FundingStage;
        location: string;
        name: string;
        id: string;
        linkedinUrl: string | null;
        industries: string[];
        createdAt: Date;
        updatedAt: Date;
        tagline: string | null;
        description: string | null;
        website: string | null;
        foundedYear: number | null;
        teamSize: number | null;
        totalFunding: number | null;
    }>;
}
