# Build stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY apps/admin/package*.json ./
RUN npm ci
COPY apps/admin/ ./
RUN npm run build

# Production stage
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3001
CMD ["node", "server.js"]
