"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const controller_1 = require("./controller");
const router = (0, express_1.Router)();
const controller = new controller_1.LinkedInController();
router.post('/connect', controller.connect);
router.post('/message', controller.sendMessage);
router.get('/profile', controller.getProfile);
exports.default = router;
